export const seedUsers = [
  { id: "user-jere", username: "JereD02", password: "Mjere02", displayName: "Jeremias", role: "admin" as const, active: true },
  { id: "user-gexa", username: "GexaD01", password: "Mgexa01", displayName: "Gexandra", role: "admin" as const, active: true },
  { id: "user-admin", username: "admin", password: "admin090304", displayName: "Administrador", role: "admin" as const, active: true },
  { id: "user-caja", username: "Caja", password: "Caja01", displayName: "Caja", role: "caja" as const, active: true },
];

export const seedProducts = [
  {
    id: "LEX-GS-001",
    nombre: "Elixir Rosa Medianoche",
    marca: "Lexy Glow",
    descripcion: "Suero reparador nocturno con acido hialuronico y extractos botanicos.",
    categoria: "Cuidado de Piel",
    costo: 78,
    precio: 120,
    precioMayorista: 102,
    stock: 85,
    stockMinimo: 18,
  },
  {
    id: "LEX-HM-042",
    nombre: "Bruma Esencia Hidratante",
    marca: "Hydra Mist",
    descripcion: "Bruma facial de uso diario para hidratar y refrescar la piel.",
    categoria: "Cosméticos",
    costo: 28,
    precio: 45,
    precioMayorista: 38,
    stock: 12,
    stockMinimo: 15,
  },
  {
    id: "LEX-VC-088",
    nombre: "Crema Noche Terciopelo",
    marca: "Velvet Care",
    descripcion: "Crema nutritiva intensiva para rutina nocturna.",
    categoria: "Cuidado de Piel",
    costo: 52,
    precio: 85,
    precioMayorista: 72,
    stock: 0,
    stockMinimo: 10,
  },
  {
    id: "LEX-BR-015",
    nombre: "Brocha Precision Seda",
    marca: "Salon Tools",
    descripcion: "Brocha profesional para aplicaciones detalladas y acabados finos.",
    categoria: "Herramientas",
    costo: 18,
    precio: 32,
    precioMayorista: 26,
    stock: 142,
    stockMinimo: 30,
  },
];
